name: Rails Tests and Lint

on:
  push:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.4.7'
        bundler-cache: true

    - name: Set up Node
      uses: actions/setup-node@v4
      with:
        node-version: '24'
        cache: 'yarn'

    - name: Enable Corepack
      run: corepack enable

    - name: Install JS dependencies
      run: yarn install --immutable

    - name: Set up Chrome
      uses: browser-actions/setup-chrome@v2

    - name: Prepare DB
      run: bin/rails db:prepare

    - name: Build CSS
      run: yarn run build:css

    - name: Reset changes from previous steps
      run: git checkout .

    - name: Run Lint
      run: bash bin/lint

    - name: Check for uncommitted changes
      run: |
        git diff --exit-code || (echo "Lint found issues and fixed them. Please commit the changes." && exit 1)

    - name: Run RSpec tests
      env:
        RAILS_ENV: test
      run: bundle exec rspec
