name: Deploy

on:
  workflow_run:
      workflows: ["Rails Tests and Lint"]  # ← さっきのファイルの名前を正確に書く
      branches: [main]
      types: 
        - completed

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.4.7'
          bundler-cache: true

      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Install Kamal
        run: gem install kamal

      - name: Create secrets file
        run: |
          mkdir -p .kamal
          echo "KAMAL_REGISTRY_PASSWORD=${{ secrets.KAMAL_REGISTRY_PASSWORD }}" > .kamal/secrets
          echo "RAILS_MASTER_KEY=${{ secrets.RAILS_MASTER_KEY }}" >> .kamal/secrets
          echo "SERVER_IP=${{ secrets.SERVER_IP }}" >> .kamal/secrets
          echo "GITHUB_CLIENT_ID=${{ secrets.GITHUB_CLIENT_ID }}" >> .kamal/secrets
          echo "GITHUB_CLIENT_SECRET=${{ secrets.GITHUB_CLIENT_SECRET }}" >> .kamal/secrets
          
      - name: Add known hosts
        run: |
          source .kamal/secrets
          ssh-keyscan -t ed25519 -H $SERVER_IP >> ~/.ssh/known_hosts

      - name: Deploy with Kamal
        run: kamal deploy
